name: Update to next release
on:
  milestone:
    types: [created]

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: contains(github.event.milestone.description, 'Release')
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        ref: master
    - name: Create new release folder
      run: |
        name=$(echo ${{ github.event.milestone.due_on }} | cut -d- -f-2)
        cd news/scripts
        ./applyTemplate.sh ${{ github.event.milestone.title }} $name
    - name: Create Pull Request for Release ${{ github.event.milestone.title }}
      uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
      with:
        author: Eclipse Releng Bot <releng-bot@eclipse.org>
        commit-message: Prepare Release ${{ github.event.milestone.title }}
        branch: prepare_R${{ github.event.milestone.title }}
        title: Prepare Release ${{ github.event.milestone.title }}
        body: A new Release Milstone was created, please review the changes and merge if appropriate.
        delete-branch: true
        milestone: ${{ github.event.milestone.number }}

